### PR TITLE
update outdated Tauri logo 

### PR DESCRIPTION
**Pull request by vasfvitor**
Hi, logos sourced from https://tauri.app/about/trademark/#assets

## Goal
Update Tauri logos
## Screenshots
https://github.com/bestofjs/bestofjs/compare/develop...vasfvitor:tauri-logo?diff=unified&w=
image

Thanks

### CODE REVIEW

**Comment by michaelrambeau** [comment]
Thank you very much @vasfvitor the updated logos are nice and the files are lighter than before 👍 !

It's a small detail but project logos in _Best of JS_ are supposed to be squares (same width and height) but the new logo's view box is 206px x 231px., which can cause a slight deformation in the browser (that I cannot see on the screen, to be honest 😅 )

Would it be possible to adjust the view box and dimension to make them squares?

image

**Comment by vasfvitor** [comment]
sure, done

**Comment by vasfvitor** [comment]
sure, done

**Comment by michaelrambeau** [comment]
> sure, done

Thank you very much Vitor @vasfvitor , you are good with SVGs! 🎉 

I'm curious if you have any tool you recommend to do this kind of manipulation (basically center an existing SVG inside a given viewbox) because I often have to do this when I add new logos.

**Comment by vasfvitor** [comment]
I just opened it on inkscape, resized the canvas (file -> document settings, I guess), centered with align tool, and exported as plain svg. Then [svgo](https://jakearchibald.github.io/svgomg/) and with the default settings plus disabled "Remove Viewbox" and "Rewrite Path". So, not one tool, for one off edits is ok.

**Comment by michaelrambeau** [comment]
Thank you @vasfvitor , I will have a look at Inkscape then, I use a lot the SVGO too, it's super convenient indeed!

The changes are online, please check!

**Comment by vasfvitor** [comment]
It's perfect, thank you @michaelrambeau!

**Pull request merged**
