### PR TITLE
Use Klass instead of CVA

### LINKED ISSUE #248: Use Klass instead of CVA
Use [klass](https://github.com/flamrdevs/klass) instead of cva for class variant utility.

See [benchmark](https://github.com/flamrdevs/klass-benchmark).

Klass also has more features such as `groups` and `slots` that can be used on compound components pattern like DropdownMenu.

### PR DESCRIPTION
**Pull request by flamrdevs**
## Goal

- Fixes #248 

Improve performance by replacing class variant utility library from cva to klass.

Other changes :
- Add custom tailwind intellisense.
- Refactor Button component with `klassed` API, this change polymorphic behavior from `asChild` prop to `as` prop.
- Refactor some components that use buttonVariants to remove `cn` util, since the buttonVariants is pre-configured to handle twMerge internally

## How to test

Ensure the class output is as expected

### CODE REVIEW

**Review by michaelrambeau — APPROVED** [review]
Thank you very much for the refactoring @flamrdevs that is a lot of work!

So to sum up the changes:

- Now `buttonVariants` helper, used to styles links as buttons, can compose class names, `cn` helper is no more needed
- `klass` is used to create the variants of the UI components instead of `cva` (note: the current code comes `shadcn/ui` code base)
- you changed the VSCode setup to get autocomplete about classNames when calling `klass` function

Anything I'm missing about the scope of the PR?

Also I appreciate that you split some long strings into array elements, for readability.

I have checked the bundle size when running the `build` command locally, it seems it has no effect, so it's good!

**Comment by michaelrambeau** [comment]
@flamrdevs I'm going to merge your PR thank you again! 🎉 

Also I will add your project to _Best of JS_, if you are OK? (following what I said in the issue)

We can talk on Discord if you want to discuss about _Best of JS_, you'd be welcome :)

**Comment by flamrdevs** [comment]
Of course, it's OK. Thank you @michaelrambeau.
Nice to see `Klass` on the _Best of JS_ list
I also have plans to contribute again to improve some visual display details.

**Comment by michaelrambeau** [comment]
`Klass` will be available on _Best of JS_ very soon! (we need 2 days of data to be able to show at the "daily trends").

About visual details, I'm working right now on integrating the color scale from Radix, FYI.

**Comment by flamrdevs** [comment]
FYI too, Im also built this library, currently the selector is not fully customizable yet, but it support light/dark theme and color aliasing as many as you want.
Check this out [coloradix](https://github.com/coloradix/coloradix), you might be interested.
And for [Tailwind](https://github.com/coloradix/coloradix/tree/main/packages/tailwindcss)

**Comment by michaelrambeau** [comment]
@flamrdevs `Klass` is now available on _Best of JS_, please check

https://bestofjs.org/projects?tags=classname

**Comment by flamrdevs** [comment]
@michaelrambeau Thanks, this cool.

But why, there's incorrect information about the bundle size. It should only about 1-2KB in BundleJS and Bundlephobia.
image
Is there something wrong with the internal calculations?

**Comment by michaelrambeau** [comment]
Sorry @michaelrambeau I've just triggered an update, I don't know what was wrong before, numbers are correct now, please check again.

FYI data comes from here: https://deno.bundlejs.com/?q=@klass/core

https://bestofjs.org/projects/klass

image

**Pull request merged**
